---
title: "exploratory_visu"
author: "Alma Steireif"
date: "`r Sys.Date()`"
output: html_document
---


```{r, include=FALSE}
library(tidyverse)
library(readxl)
library(viridis)
library(stringr)
library(googlesheets4)

library(igraph)
library(ggraph)
library(tidygraph) 

library(iNEXT)
library(fossil) # helps with creating site-by-species-matrix for use with iNEXT 
```



## Pan traps
```{r load and clean data}
# read one sheet from an excel file
df <-readxl::read_excel("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/data_field/Labels_pantraps_clean.csv.xlsx", sheet = "Labels_pantraps_clean",range = "A1:AS138")

bowltrap_clean <- df %>%
  # Remove rows where 'ID_date' contains '_missing'
  filter(!str_detect(ID_date, "_missing")) %>%
  select(SITE = ID_date, 
         small = notes,
         thrips = less_1mm,
         apocrita:Polleniidae) %>% #select site names, notes and all the taxa columns
  mutate(spider = if_else(is.na(spider), 0, spider))%>% # remove NAs from spider column
  separate(SITE, 
           into = c("Site", "Transect", "Color", "Date"), #separate site names into site, transect, color and date 
           sep = "_", 
           remove = FALSE)%>% #keep original column
    mutate(
    Date = as.Date(Date, format = "%d.%m.%Y") #format date
  )

rm(df)
```

```{r clean data}
# Step 1: Clean and process the `small` column
bowltrap_clean <- bowltrap_clean %>%
  mutate(small = str_remove(small, "small: ")) %>%  # Remove "small: " prefix
  mutate(small = str_replace_all(small, "none", "")) %>%  # Replace "none" with an empty string
  separate_rows(small, sep = ", ") %>%  # Split rows into individual entries
  
  # Step 2: Split counts and insect names
  separate(small, into = c("count", "insect"), sep = " ", extra = "merge", fill = "right") %>%
  
  # Step 3: Handle invalid `count` values
  mutate(
    count = as.numeric(count),  # Convert `count` to numeric
    insect = ifelse(is.na(count), NA, insect)  # Remove `insect` if `count` is invalid
  ) %>%
  filter(!is.na(count) & !is.na(insect)) %>%  # Remove rows with invalid counts or insects
  
  # Step 4: Pivot into wide format
  pivot_wider(names_from = insect, values_from = count, values_fill = 0, names_prefix = "small_") %>%

  # Sum thrips and small_thrip
  mutate(small_thrip = coalesce(small_thrip, 0) + coalesce(thrips, 0)) %>%  
  select(-thrips,-small_) %>%  # Optionally remove the original thrips column
  
  #sum bombus and bees
  mutate(symphyta = coalesce(symphyta, 0) + coalesce(tenthredinidae,0)) %>% 
  mutate(apocrita = coalesce(apocrita, 0) + coalesce(proctotrupidae ,0)) %>%
  select(-proctotrupidae, -tenthredinidae, -spider, -cicadellidae)

```

```{r large insects}
#create subset of data only for larger than 3mm insects
bowl_large <- bowltrap_clean %>%
  select(Site:Polleniidae) %>%
  pivot_longer(cols =  apocrita:Polleniidae,  
               names_to = "Taxa", 
               values_to = "Count") 

ggplot(bowl_large, aes(x = Taxa, y = Count, fill = Site)) +
  geom_bar(stat = "identity") +
  labs(title = "Stacked Taxa Counts by Sampling Event",
       x = "Sampling Event",
       y = "Total Count") +
  theme_minimal() +
  scale_fill_viridis(discrete = TRUE, option= "plasma") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 70), n.breaks =8)


#the platform categories are quite different than families, so let's convert these categories to something similar so we can compare

plat_bowl_large <- bowl_large %>%
  mutate(category = case_when(
    Taxa %in% c("cantharidae", "carabidae", "curculionidae", "elateridae","mordellidae", "staphylinidae") ~ "beetle",
    Taxa %in% c("hemiptera") ~ "bug",
    Taxa %in% c("diptera","calliphoridae","cecidomyiidae","tachinidae","calliphoridae","Sepsidae","Ephydridae","Muscidae","Asilidae","Stratiomyidae", "Polleniidae" ) ~ "fly",
    Taxa %in% c("dasypoda","apidae") ~ "bee",
    Taxa %in% c("sarcophagidae") ~ "fly_sarco",
    Taxa %in% c("symphyta","apocrita") ~ "wasp",
    Taxa %in% c("Empididae") ~ "fly_empi",
    TRUE ~ Taxa
  ))

ggplot(plat_bowl_large, aes(x = reorder(category, -Count), y = Count, fill = Site)) +
  geom_bar(stat = "identity",na.rm=TRUE ) +
  labs(title = "Pan traps: Stacked Taxa Counts per Site",
       x = "Taxa",
       y = "Total Count") +
  theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 70))
```

```{r small insects}
bowl_small <- bowltrap_clean %>%
  select(Site:Date, small_thrip:small_staphylinidae) %>%
  
  mutate(small_diptera = coalesce(small_fly, 0) + coalesce(small_cecidomyiidae, 0)) %>%  
  mutate(small_coleoptera = coalesce(small_beetle, 0) + coalesce(small_staphylinidae, 0)) %>%
  mutate(small_hemiptera= coalesce(small_aphid, 0) + coalesce(small_hemiptera, 0)) %>%
  
  select(-small_fly, -small_cecidomyiidae, -small_aphid, -small_staphylinidae, -small_beetle) %>%
  
  pivot_longer(cols =  small_thrip:last_col(),  
               names_to = "Taxa",
               values_to = "Count")
#plots
ggplot(bowl_small, aes(x = Site, y = Count, fill = Taxa)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Taxa Counts by Sampling Event",
       x = "Taxa",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(bowl_small, aes(x = Site, y = Count, fill = Taxa)) +
  geom_bar(stat = "identity") +
  labs(title = "Stacked taxa Counts by Sampling Event",
       x = "Sampling Event",
       y = "Total Count") +
  theme_minimal() +
  scale_fill_viridis(discrete = TRUE, option= "plasma") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### iNext - rarefaction curves
- iNEXT focuses on three measures of Hill numbers of order q: 
    + species richness (q = 0), 
    + Shannon diversity (q = 1, the exponential of Shannon entropy) 
    + Simpson diversity (q = 2, the inverse of Simpson concentration)    
 
[Source](https://cran.r-project.org/web/packages/iNEXT/vignettes/Introduction.html) 

```{r rarefaction curves for pan traps}
bowl_large2 <- as.data.frame(bowl_large) #make 'dat' into a data frame that can be read by create.matrix

bowl_large2 <- bowl_large2 %>%
        mutate(Site_type = case_when( #adding site_type column
                Site %in% c("WED", "KOT", "WDG", "BUH") ~ "young_restored", #young restored sites
                Site %in% c("STP", "JEP", "DES", "HLI", "WUP") ~ "reference", #reference sites
                TRUE ~ NA_character_)) # Default case, if needed

bowl_large2 <-subset(bowl_large2, bowl_large2[6]!=0) #remove rows with empty values in the 'family' column

#rarefaction curves for site_type ---------------------------------------------
matrix_bowl_type <- create.matrix(x = bowl_large2,
                                tax.name = 'Taxa',
                                locality = 'Site_type',
                                abund = TRUE,
                                abund.col = 'Count')
##Check your work
identical(sum(matrix_bowl_type),sum(bowl_large2$Count))
#both have 105 interactions

# Convert to data.frame for use with iNEXT
matrix_bowl_type <- as.data.frame(matrix_bowl_type)

#run iNEXT to get the diversity estimates per SITE_TYPE
set.seed(2022);iNEXT_output_insects <- iNEXT(matrix_bowl_type,  q = c(0,1,2), datatype = 'abundance') #set seed for reproducibility, iNEXT include all three indices of diversity

# This are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst 

# Plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

#save the plot
rarefaction_bowl_sitetype <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Pan traps: rarefaction curves per site type") 
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_bowl_sitetype.png")

rm(matrix_bowl_type, rarefaction_bowl_sitetype) #remove the matrix and plot to clear up memory

#rarefaction curves for site ---------------------------------------------
matrix_bowl_site <- create.matrix(x = bowl_large2,
                                tax.name = 'Taxa',
                                locality = 'Site',
                                abund = TRUE,
                                abund.col = 'Count')
##Check your work
identical(sum(matrix_bowl_site),sum(bowl_large2$Count))
#both have 105 interactions

# Convert to data.frame for use with iNEXT
matrix_bowl_site <- as.data.frame(matrix_bowl_site)

#run iNEXT to get the diversity estimates per SITE
set.seed(2022);iNEXT_output_insects <- iNEXT(matrix_bowl_site,  q = c(0,1,2), datatype = 'abundance')  #set seed for reproducibility, iNEXT include all three indices of diversity

# This are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst

# Plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

# Save the plot
rarefaction_bowl_site <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Pan traps: rarefaction curves per site")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_bowl_site.png")

rm(matrix_bowl_site, rarefaction_bowl_site) #remove the matrix and plot to clear up memory

#rarefaction curves for transect ---------------------------------------------  
matrix_bowl_transect <- create.matrix(x = bowl_large2,
                                tax.name = 'Taxa',
                                locality = 'Transect',
                                abund = TRUE,
                                abund.col = 'Count')

##Check your work
identical(sum(matrix_bowl_transect),sum(bowl_large2$Count)) #both have 105 interactions

# Convert to data.frame for use with iNEXT
matrix_bowl_transect <- as.data.frame(matrix_bowl_transect)

#run iNEXT to get the diversity estimates per transect number
set.seed(2022);iNEXT_output_insects <- iNEXT(matrix_bowl_transect,  q = c(0,1,2), datatype = 'abundance') #set seed for reproducibility, iNEXT include all three indices of diversity

# This are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst

# Can also plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

# save the plot
rarefaction_bowl_transect <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q") +
  ggtitle("Pan traps: rarefaction curves per transects")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_bowl_transect.png")

rm(matrix_bowl_transect, rarefaction_bowl_transect) #remove the matrix and plot to clear up memory

#rarefaction curves for bowl color ---------------------------------------------
matrix_bowl_color <- create.matrix(x = bowl_large2,
                                tax.name = 'Taxa',
                                locality = 'Color',
                                abund = TRUE,
                                abund.col = 'Count')

##Check your work
identical(sum(matrix_bowl_color),sum(bowl_large2$Count)) #both have 105 interactions

# Convert to data.frame for use with iNEXT
matrix_bowl_color <- as.data.frame(matrix_bowl_color)

set.seed(2022);iNEXT_output_insects <- iNEXT(matrix_bowl_color,  q = c(0,1,2), datatype = 'abundance') 
#set seed for reproducibility, iNEXT include all three indices of diversity
# iNEXT_output_insects$AsyEst # AsyEst gives the diversity estimates with their confidence intervals

#plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q") 

#save the plot
rarefaction_bowl_color <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Pan traps: rarefaction curves per bowl color")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_bowl_color.png")

rm(matrix_bowl_color, rarefaction_bowl_color) #remove the matrix and plot to clear up memory
```

## Transect netting
include=FALSE

```{r load transect data,include=FALSE}
#load data
 #Read google sheets data into R
net_data <-read_sheet("https://docs.google.com/spreadsheets/d/1YDOoUobRU6A36um0-iut6kY77X0jEMYXtFWR3-Zankc/edit?usp=sharing", sheet=2) #sheet 2 has the interaction data
```

```{r clean transect data}
net_data <- net_data %>%
  select(site = Site, transect = Transect, final_ID = final_ID, plant_species=plant_species, field_ID=pollinator_field_ID, observed =observed, collected=collected, family=Family) #select columns of interest

net_data <- net_data %>%
        mutate(site_type = case_when( #adding site_type column
                site %in% c("WED", "KOT", "WDG", "BUH") ~ "young_restored", #young restored sites
                site %in% c("STP", "JEP", "DES", "HLI", "WUP") ~ "reference", #reference sites
                TRUE ~ NA_character_)) %>%# Default case, if needed
        # new column with observed + collected interactions = total interactions
        mutate(total_interaction = coalesce(observed, 0) + coalesce(collected, 0))%>% 
        # Standardize the `Family` column to unify textual variations
        mutate(family = case_when(
               family %in% c("Muscidae c.f.", "Muscidae (c.f)", "Muscidae") ~ "Muscidae",  
               family %in% c("Tachinidae", "Tachinidae (c.f)") ~ "Tachinidae",
               family %in% c("Calliphoridae", "Calliphoridae c.f.") ~ "Calliphoridae",
               family %in% c("Mellitidae", "Melittidae") ~ "Melittidae",
               family %in% c("Fanniidae", "Faniidae") ~ "Fanniidae",
               family %in% c("Sarcophagidae c.f.", "Sarcophagidae") ~ "Sarcophagidae",
               family %in% c("Tenthrenidae", "Tenthredinidae") ~ "Tenthredinidae",
               TRUE ~ family))  # Keep other families unchanged
```

```{r interaction counts and plot}
# Interaction counts by site ----------------------------------------------
# Summarize to get the count of species per site
interaction_counts_site <- net_data %>%
  # Group by SITE and standardized family name (fam), then count interactions
  group_by(site, family) %>%
  summarize(interaction_count = n(), .groups = 'drop') #summarize the data
  
ggplot(interaction_counts_site, aes(x = site, y = interaction_count, fill = family)) +
  geom_bar(stat = "identity") +
  labs(title = "Stacked Species Counts by Sampling Event",
       x = "Sampling Event",
       y = "Total Count") +
  theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Interaction counts by plant species ---------------------------------------------- 
# Summarize to get the count of interaction between insect and plant species
interaction_counts_plants <- net_data %>%
  # Group by SITE and standardized family name (fam), then count interactions
  group_by(plant_species, family) %>%
  summarize(interaction_count = n(), .groups = 'drop')
  
# plot the data according to plant species
ggplot(interaction_counts_plants, aes(x = reorder(plant_species, interaction_count), y = interaction_count, fill = family)) +
  geom_bar(stat = "identity") +
  labs(title = "Stacked Species Counts by flower species",
       x = "Site",
       y = "Total Count") +
  theme_minimal() +
  scale_fill_viridis(discrete = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  coord_flip()
rm(interaction_counts_plants)
```

```{r transect plot}
# Create a frequency table for pol_ID
fam_counts <- table(interaction_counts_site$family)

# Convert the table to a dataframe
fam_counts_df <- as.data.frame(table(interaction_counts_site$family))
colnames(fam_counts_df) <- c("fam_ID", "frequency")

# Create the bar plot
ggplot(fam_counts_df, aes(x = fam_ID, y = frequency, width=.7)) +
  geom_col(fill= "skyblue") + # Create the bar plot
  geom_text(aes(label = frequency), vjust = -0.5, size = 4) + # Add labels above bars
  labs(
    title = "Counts per Family",
    x = "Pollinator ID",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

sum(fam_counts_df$Frequency);length(fam_counts_df$fam_ID);levels(as.factor(interaction_counts_site$family))
rm(fam_counts, fam_counts_df,interaction_counts_site)
```

### iNext - rarefaction curves
```{r rarefaction curves for transect netting}
# rarefaction curves for site_type ---------------------------------------------
net_data <- as.data.frame(net_data) #make 'dat' into a data frame that can be read by create.matrix

net_data<-subset(net_data, net_data[8]!="") #remove rows with empty values in the 'family' column

matrix_netting_type <- create.matrix(x = net_data,
                                tax.name = 'family',
                                locality = 'site_type',
                                abund = TRUE,
                                abund.col = 'total_interaction')
##Check your work
identical(sum(matrix_netting_type),sum(net_data$total_interaction))
#both have 2427 interactions

# Convert to data.frame for use with iNEXT
matrix_netting_type <- as.data.frame(matrix_netting_type)

# Run iNEXT to get the diversity estimates per SITE_TYPE
set.seed(2022);iNEXT_output_insects <- iNEXT(matrix_netting_type,  q = c(0,1,2), datatype = 'abundance')#set seed for reproducibility, iNEXT include all three indices of diversity

# this are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst 
# Can also plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

#save the plot
rarefaction_netting_sitetype <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Netting: rarefaction curves per site type")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_netting_sitetype.png")

rm(matrix_netting_type, rarefaction_netting_sitetype)

# rarefaction curves for sites ----------------------------------------------
matrix_netting_site <- create.matrix(x = net_data,
                                tax.name = 'family',
                                locality = 'site',
                                abund = TRUE,
                                abund.col = 'total_interaction')
##Check your work
identical(sum(matrix_netting_site),sum(net_data$total_interaction))
#both have 2427 interactions

# Convert to data.frame for use with iNEXT
matrix_netting_site <- as.data.frame(matrix_netting_site)

# Run iNEXT to get the diversity estimates per SITE 
set.seed(2022); iNEXT_output_insects <- iNEXT(matrix_netting_site,  q = c(0,1,2), datatype = 'abundance') #set seed for reproducibility, iNEXT include all three indices of diversity

# this are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst 

# Plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

#save the plot
rarefaction_netting_site <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Netting: rarefaction curves per site")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_netting_site.png")

rm(matrix_netting_site, rarefaction_netting_site) #remove the matrix and plot to clear up memory

# rarefaction curves for transect number ---------------------------------------------
matrix_netting_transect <- create.matrix(x = net_data,
                                tax.name = 'family',
                                locality = 'transect',
                                abund = TRUE,
                                abund.col = 'total_interaction')
##Check your work
identical(sum(matrix_netting_transect),sum(net_data$total_interaction))
#both have 2427 interactions

# Convert to data.frame for use with iNEXT
matrix_netting_transect <- as.data.frame(matrix_netting_transect)

#run iNEXT to get the diversity estimates per transect number
set.seed(2022); iNEXT_output_insects <- iNEXT(matrix_netting_transect,  q = c(0,1,2), datatype = 'abundance') #set seed for reproducibility, iNEXT include all three indices of diversity

# This are specifically the diversity estimates with their confidence intervals:
# iNEXT_output_insects$AsyEst 

# plot the results
ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")

#save the plot
rarefaction_netting_transect <- ggiNEXT(iNEXT_output_insects, type = 1, color.var = 'Assemblage',facet.var="Order.q")+
  ggtitle("Netting: rarefaction curves per transects")
ggsave("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/figures/rarefaction_netting_transect.png")

rm(matrix_netting_transect, rarefaction_netting_transect) #remove the matrix and plot to clear up memory 
```
```{r}
rm(iNEXT_output_insects,bowl_large2)
```

