---
title: "platform_pan_comp"
author: "Alma Steireif"
date: "`r Sys.Date()`"
output: html_document
---

### libraries
```{r, include=FALSE}
library(tidyverse)
library(ggalluvial)
library(vegan)
library(emmeans)
```

### data
```{r}
load("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/data/20250203_full_bowltrap.RData")
load("C:/Users/Almas/Desktop/UNI_LEIPSI/Thesis/Thesis_Rproject/data/20250130_platform_cams.RData")
```

### data cleaning
```{r}
bowltrap <- bowltrap_clean %>% 
  #select all columns except "small_" and "Color"
  select(1:31, -Color, -SITE) %>%

   #pivot into long format
   pivot_longer(cols =  apidae:acalyptrate,  
               names_to = "Taxa", 
               values_to = "Count") %>%
  
  # adapt taxa categories to the ones used in platform data (less precise)
  mutate(Category = case_when(
    Taxa %in% c("cantharidae", "carabidae", "curculionidae", "elateridae",
                "mordellidae", "staphylinidae") ~ "beetle",
    Taxa %in% c("coccinellidae") ~ "beetle_cocci",
    Taxa %in% c("hemiptera") ~ "bug",
    Taxa %in% c("diptera","calliphoridae","cecidomyiidae","tachinidae","calliphoridae",
                "sepsidae","ephydridae","muscidae","asilidae","stratiomyidae", "polleniidae","acalyptrate" ) ~ "fly",
    Taxa %in% c("dasypoda","apidae","colletidae") ~ "bee_apis",
    Taxa %in% c("bombus") ~ "bee_bombus",
    Taxa %in% c("sarcophagidae") ~ "fly_sarco",
    Taxa %in% c("symphyta","apocrita","proctotrupidae","tenthredinidae") ~ "wasp",
    Taxa %in% c("empididae") ~ "fly_empi",
    TRUE ~ Taxa
    )) %>%
  #remove all rows that have a 0 "count" value
  filter(Count != 0) %>%
  
  #combine repeat rows because we removed the color column
  group_by(Site, Site_type,Transect, Date, Category) %>%
  summarise(Count = sum(Count))

platform <- platform_cams_save %>%
  select(Site=site, Site_type=site_type, Transect=transect,Date= date, Category= top1) %>%
  #create a new "Count" column that sums up the identical rows
  group_by(Site, Site_type,Transect, Date, Category)%>%
  summarise(Count = n())
```


```{r combining data}
# adding a methods colums to both data sets
bowltrap$Method <- "bowl_trap"
platform$Method <- "platform_camera"

#combining the two data sets
BP_combined <- rbind(bowltrap, platform)
rm(bowltrap_clean, platform_cams_save)
```


```{r plotting}
#plotting the data
BP_combined %>%
  ggplot(aes(x = Site, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Site_type) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Comparison of the two sampling methods",
       x = "Site",
       y = "Count")

BP_combined %>%
  ggplot(aes(x = Site, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(Site_type ~ Method) +  # This will facet based on the collection method and site_type
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Comparison of the two sampling methods",
       x = "Site",
       y = "Count")

BP_combined %>%
  ggplot(aes(axis1 = Site, axis2 = Method, y = Count, fill = Category)) +
  geom_alluvium(aes(fill = Category)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal() +
  labs(title = "Insect Counts by Collection Method and Category",
       x = "Sampling Stage",
       y = "Count")


```

```{r}
# change dataframe format to perform stat test
#each type of category now becomes a columm
BP_combined_wide <- BP_combined %>%
  #grouping by site, site_type, transect, date
  group_by(Site, Site_type,Transect, Date) %>%
  pivot_wider(names_from = Category, values_from = Count, values_fill = 0) %>%
  ungroup()%>%
  select(-Transect)%>%
  #move Date column to the first position
  relocate(Date, .before = Site)

colnames(BP_combined_wide)

#adding a column for species richness and shannon index
BP_combined_wide <- BP_combined_wide %>%
  mutate(Richness = rowSums(select(., -Site, -Site_type, -Date, -Method)),
         Shannon = diversity(select(., -Site, -Site_type, -Date, -Method), index = "shannon"))

#checking distribution and normality of shannon index
hist(BP_combined_wide$Shannon)  # Histogram
qqnorm(BP_combined_wide$Shannon); qqline(BP_combined_wide$Shannon)  # Q-Q Plot
shapiro.test(BP_combined_wide$Shannon)  # Shapiro-Wilk test (p > 0.05 means normal)
#not normal, even after log transformation and square root transformation


# checking for overdispersion Poisson GLM
mean_richness <- mean(BP_combined_wide$Richness)
var_richness <- var(BP_combined_wide$Richness)
cat("Mean:", mean_richness, "Variance:", var_richness) #variance >> mean

#Negative Binomial GLM in R
library(MASS)

# Fit Negative Binomial GLM
glm_nb <- glm.nb(Richness ~ Site_type * Method * Site, data = BP_combined_wide)

# Print summary of model
summary(glm_nb)

# Plot residuals
plot(glm_nb$fitted.values, residuals(glm_nb), main = "Residuals vs Fitted Values",
     xlab = "Fitted Values", ylab = "Residuals", pch = 20)
abline(h = 0, col = "red")
# Good fit: Residuals should be randomly scattered around 0.

#plot
ggplot(BP_combined_wide, aes(x = Method, y = Richness, fill = Site_type)) +
  geom_boxplot() +
  facet_wrap(~ Site_type) +
  labs(title = "Effect of Method on Richness Across Site Types", 
       x = "Method", y = "Richness") +
  theme_minimal()


# Get model predictions
emm <- emmeans(glm_nb, ~ Site_type * Method)

# Convert to data frame for ggplot
emm_df <- as.data.frame(emm)

ggplot(emm_df, aes(x = Method, y = emmean, fill = Site_type)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), 
                width = 0.2, position = position_dodge(0.9)) +
  labs(title = "Predicted Richness by Method & Site Type", 
       x = "Method", y = "Predicted Richness") +
  theme_minimal()
```

```{r shannon}
# Fit Negative Binomial GLM
glm_nb <- glm.nb(Shannon ~ Site_type * Method * Site, data = BP_combined_wide)

# Print summary of model
summary(glm_nb)

# Plot residuals
plot(glm_nb$fitted.values, residuals(glm_nb), main = "Residuals vs Fitted Values",
     xlab = "Fitted Values", ylab = "Residuals", pch = 20)
abline(h = 0, col = "red")

# Good fit: Residuals should be randomly scattered around 0.

ggplot(BP_combined_wide, aes(x = Method, y = Shannon, fill = Site_type)) +
  geom_boxplot() +
  facet_wrap(~ Site_type) +
  labs(title = "Effect of Method on Richness Across Site Types", 
       x = "Method", y = "Shannon") +
  theme_minimal()

# Get model predictions
emm <- emmeans(glm_nb, ~ Site_type * Method)

# Convert to data frame for ggplot
emm_df <- as.data.frame(emm)

ggplot(emm_df, aes(x = Method, y = emmean, fill = Site_type)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), 
                width = 0.2, position = position_dodge(0.9)) +
  labs(title = "Predicted Shannon Diversity by Method & Site Type", 
       x = "Method", y = "Predicted Shannon Diversity") +
  theme_minimal()
```




```{r}
table(BP_combined_wide$Site, BP_combined_wide$Method)
summary(BP_combined_wide)

dispersion_test <- sum(residuals(glm_nb, type="pearson")^2) / glm_nb$df.residual
dispersion_test  # If > 1, overdispersion is present
```

